/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuditLog: typeof import('./src/components/reports/AuditLog.vue')['default']
    CostTypes: typeof import('./src/components/settings/CostTypes.vue')['default']
    DatabaseSettings: typeof import('./src/components/settings/DatabaseSettings.vue')['default']
    DateField: typeof import('./src/components/shared/DateField.vue')['default']
    DateRangeField: typeof import('./src/components/shared/DateRangeField.vue')['default']
    DateTimeField: typeof import('./src/components/shared/DateTimeField.vue')['default']
    DebtorsReport: typeof import('./src/components/DebtorsReport.vue')['default']
    Expenditures: typeof import('./src/components/Expenditures.vue')['default']
    GiveOut: typeof import('./src/components/GiveOut.vue')['default']
    IngredientsStockReport: typeof import('./src/components/reports/IngredientsStockReport.vue')['default']
    Item: typeof import('./src/components/settings/Item.vue')['default']
    ItemUnit: typeof import('./src/components/settings/ItemUnit.vue')['default']
    Loans: typeof import('./src/components/Loans.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Login2: typeof import('./src/components/Login2.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    MarginDashboard: typeof import('./src/components/MarginDashboard.vue')['default']
    Outlets: typeof import('./src/components/settings/Outlets.vue')['default']
    Payables: typeof import('./src/components/Payables.vue')['default']
    ProductionPlan: typeof import('./src/components/ProductionPlan.vue')['default']
    Productions: typeof import('./src/components/Productions.vue')['default']
    Products: typeof import('./src/components/settings/Products.vue')['default']
    ProfitProjection: typeof import('./src/components/ProfitProjection.vue')['default']
    Purchases: typeof import('./src/components/Purchases.vue')['default']
    QualityAdjustmentReport: typeof import('./src/components/reports/QualityAdjustmentReport.vue')['default']
    ReportsList: typeof import('./src/components/reports/ReportsList.vue')['default']
    Roles: typeof import('./src/components/settings/Roles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sales: typeof import('./src/components/Sales.vue')['default']
    SalesReport: typeof import('./src/components/reports/SalesReport.vue')['default']
    Staffs: typeof import('./src/components/Staffs.vue')['default']
    StockReport: typeof import('./src/components/reports/StockReport.vue')['default']
    StockTransfers: typeof import('./src/components/StockTransfers.vue')['default']
    TransferIntegrityCheck: typeof import('./src/components/TransferIntegrityCheck.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
  }
}
